[project]
name = "note-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [    "selenium",
    "undetected-chromedriver>=3.5.5",
    "rich>=14.0.0",
    "distutils",
]
